(()=>{const K='road95_control_v1',W=['Partial Start','Adaptation','Adaptation','Build','Build','Development','Development','Strong Week','Deload'];const D=[
['Monday','Strength + Basketball','Build strength without compromising basketball.','strength',[['Back Squat','squat'],['Bench Press','bench'],['Barbell Row','row'],['Romanian Deadlift','rdl'],['Pull-ups','pull'],['Band Lateral Raise','lateral'],['Dead Bug','deadbug'],['Basketball','basket']]],
['Tuesday','Recovery + Basketball','Absorb training load and arrive functional for basketball.','recovery',[['Easy Walk','walk'],['Ankle Rocks','ankle'],['90/90 Hip Rotations','hips'],['Cat-Camel','cat'],['Thoracic Rotations','thoracic'],['Dynamic Hip-Flexor Stretch','hipflexor'],['Wall Slides','wall'],['Easy Walk Finish','walkEnd'],['Basketball','basket']]],
['Wednesday','Motor / Aerobic Base','Build aerobic capacity at easy, recoverable intensity.','conditioning',[['Easy Aerobic Work','motor'],['Run-Walk Option','runwalk'],['Side Plank','sideplank']]],
['Thursday','Movement & Robustness + Basketball','Strengthen ankles, knees, hips and trunk.','recovery',[['Calf Raise','calf'],['Bent-Knee / Soleus Raise','soleus'],['Tibialis Raise','tibialis'],['Split Squat Isometric','splitiso'],['Single-Leg Balance','balance'],['Glute Bridge','bridge'],['Lateral Band Walk','bandwalk'],['Copenhagen Short Lever','copenhagen'],['Pallof Press','pallof'],['Mobility Flow','mobility'],['Basketball','basket']]],
['Friday','Strength B + Power','Primary weekly strength and power stimulus.','strength',[['Vertical Jump','jump'],['Deadlift','deadlift'],['Overhead Press','ohp'],['Bulgarian Split Squat','bulgarian'],['Pull-ups','pullFri'],['Incline Bench Press','incline'],['Row','rowFri'],['Biceps Curl','curl'],['Triceps Extension','triceps'],['Suitcase Carry','carry']]],
['Saturday','Athletic Development','Jump, land, accelerate and decelerate with quality.','conditioning',[['Snap Down','snap'],['Pogo Jumps','pogo'],['Broad Jump','broad'],['Lateral Bounds','bounds'],['Acceleration','accel'],['Deceleration','decel'],['Defensive Shuffle','shuffle'],['Bear Crawl','bear']]],
['Sunday','Off / Active Recovery','Recover and review the week.','recovery',[['Complete Rest','off'],['Optional Easy Walk','sundayWalk'],['Optional Gentle Mobility','sundayMobility'],['Weekly Check','weekly']]]];
const E={squat:['Not prescribed','50 kg · 3 × 6 · RIR 2–3','50 kg · 3 × 7 · RIR 2–3','50 kg · 3 × 8 · RIR 2–3','60 kg · 3 × 6 · RIR 2–3','60 kg · 3 × 7 · RIR 2–3','60 kg · 3 × 8 · RIR 2–3','70 kg · 3 × 5–6 only if earned','Reduce strength stress 30–50%'],bench:['Not prescribed','50 kg · 3 × 5 · RIR 2–3','50 kg · 3 × 6 · RIR 2–3','50 kg · 3 × 7 · RIR 2–3','50 kg · 3 × 8 · RIR 2–3','60 kg · 3 × 5 only if earned','60 kg · 3 × 6','60 kg · 3 × 7','Reduce strength stress 30–50%'],deadlift:['Not prescribed','50 kg · 3 × 5','50 kg · 3 × 6','50 kg · 3 × 7','50 kg · 3 × 8','55 kg · 3 × 5','55 kg · 3 × 6','55 kg · 3 × 7','40–45 kg · 2 × 5 · RIR 4–5'],ohp:['Not prescribed','25 kg · 3 × 5','25 kg · 3 × 6','25 kg · 3 × 7','25 kg · 3 × 8','27.5 kg · 3 × 5','27.5 kg · 3 × 6','27.5 kg · 3 × 7–8','20–22.5 kg · 2 × 5'],motor:['Easy only','35 min easy','35–38 min easy','40 min easy','40–42 min easy','45 min easy','45–48 min easy','50 min maximum','30–35 min easy'],jump:['Quality only','3 × 3 quality','3 × 3 quality','3 × 3 quality','3 × 3 quality','3 × 3 quality','3 × 3 quality','3 × 3 quality','2 × 2 fresh']};
const R={row:'3 × 8 → 9 → 10; add 2.5–5 kg and return to 8 · RIR 2–3',rdl:'2 × 8 → 9 → 10; add 2.5–5 kg · RIR 3',pull:'6 → 7 → 8 → 9 → 10 → 11 → 12 total reps; W8: 5–6 easy',pullFri:'6 → 7 → 8 → 9 → 10 → 11–12 → 12–14 total; W8: 5–6 easy',lateral:'2 × 12 → 15; then increase band',deadbug:'3 × 6 → 8 / side with control',sideplank:'2 × 20 sec / side; progress to 30 sec; W8: 20 sec easy',walk:'5 min easy',ankle:'2 × 10 / side',hips:'2 × 8 / side',cat:'8–10 controlled reps',thoracic:'2 × 8 / side',hipflexor:'2 × 30 sec / side',wall:'2 × 10',walkEnd:'5–10 min easy',runwalk:'2 min jog + 2 min walk; increase gradually',calf:'3 × 12–15',soleus:'3 × 12–15',tibialis:'3 × 15–20',splitiso:'2 × 20 → 30 sec / side',balance:'2 × 30 → 45 sec',bridge:'3 × 12 → 15',bandwalk:'2 × 10 → 15 steps / side',copenhagen:'2 × 15 → 30 sec / side',pallof:'2 × 10 → 15 / side',mobility:'Ankle + 90/90 + thoracic mobility',bulgarian:'3 × 8 → 12 / side; then add resistance',incline:'3 × 8 → 10; then add 2–2.5 kg',rowFri:'3 × 8 → 10; then add load',curl:'2–3 × 10–12; increase after 12 comfortable',triceps:'2–3 × 10–12; increase after 12 comfortable',carry:'3 × 20 → 30 m / side; then add load',snap:'3 × 5 quality',pogo:'3 × 10 quality',broad:'3 × 3 quality',bounds:'3 × 4 / side',accel:'6 × 10 m',decel:'4–6 quality reps',shuffle:'4 × 10–15 sec',bear:'3 × 10–15 m',basket:'As scheduled; record whether played',off:'Complete rest',sundayWalk:'20–30 min optional',sundayMobility:'5–10 min easy',weekly:'Weight · waist · sleep · fatigue'};
let S={week:0,day:0,logs:{},complete:{}};try{S={...S,...JSON.parse(localStorage.getItem(K)||'{}')}}catch(e){}let active='';const $=q=>document.querySelector(q),key=()=>`${S.week}-${S.day}`,target=id=>E[id]?.[S.week]||R[id]||'Follow the prescribed quality target',save=()=>localStorage.setItem(K,JSON.stringify(S)),show=(id,on=true)=>$('#'+id).classList.toggle('open',on),asset='https://raw.githubusercontent.com/FranklinTovar/road95-dashboard/main/assets/',thumb=id=>asset+(id==='squat'?'r95-squat.png':id==='bench'?'r95-bench.png':'r95-row.png');
function draw(){let n=(S.day+1)%7;$('#nextText').textContent=`${D[n][0].toUpperCase()} · ${D[n][1].toUpperCase()}`;$('#weekText').textContent=`WEEK ${S.week} / 8`;$('#todayTitle').textContent=D[S.day][1].toUpperCase();$('#preview').innerHTML=D[S.day][4].slice(0,3).map(([name,id])=>`<div class="exercise"><div class="thumb"><img src="${thumb(id)}" alt="${name}"></div><div><b>${name}</b><small>${target(id)}</small></div><button class="add" data-log="${id}">${S.logs[`${key()}-${id}`]?'EDIT':'ADD'} +</button></div>`).join('');document.querySelectorAll('[data-log]').forEach(b=>b.onclick=()=>logger(b.dataset.log));planner();status()}
function planner(){$('#planTitle').textContent=`Week ${S.week} · ${W[S.week]}`;$('#weeks').innerHTML=W.map((w,i)=>`<button class="${i===S.week?'active':''}" data-week="${i}">W${i}<br>${w}</button>`).join('');$('#days').innerHTML=D.map((d,i)=>`<button class="${i===S.day?'active':''}" data-day="${i}">${d[0].slice(0,3).toUpperCase()}</button>`).join('');$('#phaseLabel').textContent=`WEEK ${S.week} · ${W[S.week].toUpperCase()}`;$('#sessionTitle').textContent=`${D[S.day][0]} · ${D[S.day][1]}`;$('#sessionPurpose').textContent=D[S.day][2];$('#completeSession').textContent=S.complete[key()]?'COMPLETED ✓':'MARK COMPLETE';$('#planList').innerHTML=D[S.day][4].map(([name,id])=>`<div class="plan-row"><div><b>${name}</b><small>${target(id)}</small></div><button class="add" data-planlog="${id}">${S.logs[`${key()}-${id}`]?'EDIT':'ADD'} +</button></div>`).join('');document.querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>{S.week=+b.dataset.week;save();draw()});document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{S.day=+b.dataset.day;save();draw()});document.querySelectorAll('[data-planlog]').forEach(b=>b.onclick=()=>logger(b.dataset.planlog))}
function logger(id){active=id;let name=D[S.day][4].find(x=>x[1]===id)?.[0]||id,v=S.logs[`${key()}-${id}`]||{};$('#logTitle').textContent=name;$('#logTarget').textContent=`PLANNED: ${target(id)}`;['Weight','Sets','Reps','Rir','Feel','Notes'].forEach(x=>$('#log'+x).value=v[x.toLowerCase()]||'');show('logger')}
function status(){$('#sessionCount').textContent=`${Object.keys(S.complete).filter(k=>k.startsWith(S.week+'-')&&S.complete[k]).length} / 7`;['strength','conditioning','recovery'].forEach(t=>{$('#'+t+'Status').textContent=D.some((d,i)=>d[3]===t&&S.complete[`${S.week}-${i}`])?'● ON TRACK':'● NOT LOGGED'})}
$('#nextSession').onclick=()=>{S.day=(S.day+1)%7;save();draw();show('planner')};$('#block').onclick=()=>show('planner');$('#openToday').onclick=()=>show('planner');$('#weightButton').onclick=()=>$('#weightSystem').scrollIntoView({behavior:'smooth'});$('#completeSession').onclick=()=>{S.complete[key()]=!S.complete[key()];save();draw()};$('#saveExercise').onclick=()=>{let v={};['Weight','Sets','Reps','Rir','Feel','Notes'].forEach(x=>v[x.toLowerCase()]=$('#log'+x).value);S.logs[`${key()}-${active}`]=v;save();show('logger',false);draw()};document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('.modal').classList.remove('open'));document.querySelectorAll('.modal').forEach(m=>m.onclick=e=>{if(e.target===m)m.classList.remove('open')});$('#addMedia').onclick=()=>$('#mediaFile').click();$('#mediaFile').onchange=e=>{let f=e.target.files[0];if(f)$('#heroImage').src=URL.createObjectURL(f)};draw();
})();
